### ISSUE TITLE
cant be compiled

### ISSUE THREAD

**Issue by Tier6194** [HypedDomi/BetterDiscordStuff#18]
### Discord Account

FakeTier#0677

### Describe the bug

it doesnt work at all and says it cant be compiled

### How can I recreate this bug

1) install the plugin

**Comment by Spectroxx** [comment]
Can confirm this happens to me too.

**Comment by HypedDomi** [comment]
I'll try to look tomorrow into a few plugins

**Comment by MacGyverPY** [comment]
cant be compiled.

error:

```
TypeError: Cannot read property 'TooltipContainer' of undefined
    at eval (betterdiscord://plugins/BetterInvites.plugin.js:156:77)
    at eval (betterdiscord://plugins/BetterInvites.plugin.js:280:7)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at AsyncFunction.<anonymous> (<anonymous>:4:7155)
```

**Comment by Zzeyy** [comment]
> I'll try to look tomorrow into a few plugins

It's been 8 days, any update?

**Comment by HypedDomi** [comment]
I hadn’t time yet

**Comment by Tharki-God** [comment]
i made a pull request fixing it
